;;; !!! This configuration is handled by HelloImGui and stores several Ini Files, separated by markers like this:
           ;;;<<<INI_NAME>>>;;;

;;;<<<ImGui_655921752_Default>>>;;;
[Window][Debug##Default]
Pos=60,3
Size=400,400
Collapsed=0

[Window][Settings]
Pos=172,173
Size=312,80
Collapsed=0

[Window][Settings Setting Ranging Mode]
Pos=60,60
Size=175,52
Collapsed=0

[Window][Settings Ready]
Pos=11,404
Size=261,83
Collapsed=0

[Docking][Data]

;;;<<<Layout_655921752_Default>>>;;;
;;;<<<HelloImGui_Misc>>>;;;
[Layout]
Name=Default
[StatusBar]
Show=false
ShowFps=true
[Theme]
Name=DarculaDarker
;;;<<<SplitIds>>>;;;
{"gImGuiSplitIDs":{}}
;;;<<<AppWindow>>>;;;
[AppWindow]
DpiWindowSizeFactor=1
WindowPosition=663,195
WindowSize=876,716




